### PR TITLE
Forcibly disable location and notification access

### LINKED ISSUE #87: Unhandled browser dialogs sometimes cause crashes
When performing searches in any mode (PC, Edge, or Mobile), Bing occasionally requests a geographic location from the browser. Under some configurations, the ungandled browser dialog can trigger an `AllocateAndMapSharedMemory `exception in chrome, which causes the bot to crash.

In such cases, this can be mitigated by blocking geolocation and notification requests at the browser level.

### PR DESCRIPTION
**Pull request by andrewjmetzger**
Closes #87

### CODE REVIEW

**Comment by andrewjmetzger** [comment]
Updated code to change the browser profile settings instead of flags, which should be more reliable across future releases of Chrome. 

This is the equivalent of going to `chrome://settings/content`, selecting Location, and switching the setting to 'Off'.

**Comment by xMNG** [comment]
good update, thank you.

**Comment by MacMarde** [comment]
With the new code changes my bot is throwing constantly exceptions:

selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
Message: unexpected alert open: {Alert text : We can't access your GPS location. Set a default location to get better local results.}

Seems not to be a good solution for me. I do now have more problems than before.

**Comment by andrewjmetzger** [comment]
Interesting @MacMarde. Would you mind [opening an issue](https://github.com/xMNG/Microsoft-Rewards-Bot/issues/new) and attaching your logs so I can investigate further?

**Pull request merged**
