### PR TITLE
Change lightning_quizes

### LINKED ISSUE #29: List Index Out of Range
Been getting this error for the past couple days:

```DevTools listening on ws://127.0.0.1:49427/devtools/browser/30621e6f-f2be-483a-ad8e-9b4f8b56a3d0

DevTools listening on ws://127.0.0.1:49523/devtools/browser/c777f7d1-c84e-4c38-afd5-130a2dd2d295
Traceback (most recent call last):
  File "ms_rewards.py", line 804, in <module>
    iter_dailies()
  File "ms_rewards.py", line 514, in iter_dailies
    lightning_quiz()
  File "ms_rewards.py", line 583, in lightning_quiz
    find_by_css('.cico.btCloseBack')[0].click()
IndexError: list index out of range```

### PR DESCRIPTION
**Pull request by ShoGinn**
This is to fix the lightning quizzes

Fixes #29 and #28

### CODE REVIEW

**Comment by ShoGinn** [comment]
You might even be able to take out the if statement and just keep the elif ;)
Since no matter what the AnswerOption will always be in all quizzes..
But the code is a bit sloppy on how it just goes through the choices.. if you have a better way please assist!

**Comment by xMNG** [comment]
Thanks!! Going through the code and testing now. I just encountered the lightning quiz this weekend.

**Comment by xMNG** [comment]
I don't have a lightning quiz available to test on today (it must have expired yesterday).

What does `first_page = browser.find_element_by_id('rqAnswerOption0').get_attribute("data-serpquery")` on line 580 do?

**Comment by ShoGinn** [comment]
So to initialize the javascript my method is to pull the link from the answer and load that.

**Pull request merged**
